services:
  laravel_app:
    image: ghcr.io/fjanphilip/ci-cd-test:latest
    container_name: ci_cd_test_app
    restart: unless-stopped
    ports:
      - "9000:80"
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/storage
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  storage_data: