version: '3.8'

services:
  laravel_app:
    image: ghcr.io/fjanphilip/ci-cd-test:latest
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/storage
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  storage_data: