version: '3.8'

services:
  laravel_app:
    image: ghcr.io/fjanphilip/ci-cd-test:latest
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge